name: Testing docker image build

on:
    pull_request:
        branches: ["master", "main"]

jobs:
    deploy:
        strategy:
            fail-fast: true

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            # Build docker images
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and push release
              id: docker_build_release
              uses: docker/build-push-action@v4
              with:
                  context: .
                  platforms: linux/amd64
                  file: ./docker/Dockerfile
                  push: false
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/yaclips:latest
            - name: Build and push release(client)
              id: docker_build_release_client
              uses: docker/build-push-action@v4
              with:
                  context: ./client
                  platforms: linux/amd64,linux/arm64/v8
                  file: ./docker/Dockerfile
                  push: false
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/yaclips:latest
